### PR TITLE
Added a new variable

### PR DESCRIPTION
**Pull request by Shandeika**
Added the variable "message", which contains the user's message to which we make a response.

### CODE REVIEW

**Comment by Shandeika** [comment]
Background:
I wanted to make the construction of the answer as it was before(before the appearance of reply). The message variable did not exist at all, and the transition by inserting "\n" in the settings for some reason did not work. I made the following construction:
```> {{message}}{{newLine}}{{author}}```
It allows you to respond to a user's message in a different channel as before. Simple and clear

**Comment by QWERTxD** [comment]
Hello, thanks for putting time and effort into that, it's really appreciated.
Please bump the version and change the changelog (also credit yourself there) to commit the changes.

**Comment by Shandeika** [comment]
>  change the changelog (also credit yourself there) to commit the changes.

Sorry, but I do not know how to make a list of changes.

**Review by QWERTxD — APPROVED** [review]

**Comment by RadNotRed** [comment]
not sure why these werent merged..

**Pull request merged**
