### PR TITLE
Fixed UserVolumeBooster.plugin.js

### PR DESCRIPTION
**Pull request by jurtomasz13**
fixed variable's name to existing one
authors => author

### CODE REVIEW

**Review by HypedDomi — COMMENTED** [review]
but 
image

**Comment by jurtomasz13** [comment]
@HypedDomi wait, something is not right. when downloading it from betterdiscord.app you get the wrong version where author = "QWERT" that results in error because it tries to map on authors not author

**Comment by jurtomasz13** [comment]
image

**Comment by HypedDomi** [comment]
Yeah that is fixed

**Pull request closed without merging**
